
export const ADD_TO_CHICKIN_CART='ADD_TO_CHICKIN_CART';
export const ADD_TO_CHICK_OUT_CART='ADD_TO_CHICK_OUT_CART';
export const REMOVE_FROM_ALLRESOURCES_CART='REMOVE_FROM_ALLRESOURCES_CART';
export const REMOVE_FROM_CHECKIN_CART='REMOVE_FROM_CHECKIN_CART';
export const REMOVE_FROM_CHECKOUT_CART='REMOVE_FROM_CHECKOUT_CART';





